spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sis_financeiro
    username: root
    password: ${USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
